Front end proposed changes for query display
endeavourhealth-discovery/IMDirectory pull request #2159
Opened 2024-10-07 16:20 UTC by DavidStables

Proposed front end changes as in document for a more flexible query display

2024-10-08 08:16 UTC, kkardatos approved these changes

2024-10-09 10:06 UTC, VororJo approved these changes

2024-10-09 15:25 UTC, matt-voror requested changes

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +        v-for="(nestedWhere,index) in match.where"
if and for

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +    <span v-if="match.includeIf" :class="'then'">{{ match.includeIf }}</span>
no binding on string classes

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +const list: Ref<Match[]> = ref([]);
too generic name

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +const op: Ref<any> = ref();
naming

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +const op1: Ref<any> = ref();
naming

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +// Watch for changes in the prop and update the local copy accordingly
Missing TODO functionality?

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +  color : rgb(72,32,92)
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +  color : rgb(180, 48, 190);
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +  color: lightseagreen;
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +  color: mediumslateblue;
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +<style>
replace global style sheet with :deep styles in scoped section and use theme colors
https://vuejs.org/api/sfc-css-features.html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveQueryDisplay.vue
> +      <span v-if="query.name" style="padding-left:2rem;" v-html="query.name"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveMatchDisplay.vue
> +    <span v-if="match.orderBy" :class="'field'"v-html="match.orderBy.description"></span>
incorrect use of v-html on standard string
v-html is a potential security issue and is used to render secure html strings only.
Use `<pre></pre>` element if you need string formating

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveQueryDisplay.vue
> +      <IMFontAwesomeIcon
see prev example

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveQueryDisplay.vue
> +       <span v-if="query.name" v-html="query.name"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveQueryDisplay.vue
> +      <div style="color: green;padding-left: 2rem">Fields (columns)</div>
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveQueryDisplay.vue
> +const list: Ref<Match[]> = ref([]);
naming

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveReturnDisplay.vue
> +  color: lightseagreen;
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +      <span v-html="getOperator(property.inlineOperator,propertyIndex,secondProperty)"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +      <span v-if="property.name" :class="'field'" v-html="property.name"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +       <span v-if="property.qualifier" :class="'value-field'" v-html="property.qualifier"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +        <span v-if="property.valueLabel" v-html="getFormattedValue(property)"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +             <span :class="'field'" v-html="property.relativeTo.qualifier"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +           <span :class="'node-ref'" v-html="property.relativeTo.nodeRef"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +         <span v-if="property.nodeRef" :class="'node-ref'" v-html="property.nodeRef"></span>
incorrect use of v-html

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +          v-for="(nestedProperty, index) of property.where"
if & for

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +const list: Ref<Node[]> = ref([]);
naming

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +const op: Ref<any> = ref();
naming

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +const op1: Ref<any> = ref();
naming

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +const clickedProperty: Ref<Where> = ref({} as Where);
type is Where | undefined. Reformat to use undefined not empty object

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color : rgb(0, 102, 102);
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color : rgb(180, 48, 190);
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color: rgb(138, 67, 138) !important;
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color: blue;
theme color

2024-10-09 15:25 UTC, matt-voror commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color: orange;
theme color

2024-10-17 11:33 UTC, DavidStables commented on ui/src/components/directory/viewer/QueryDisplay.vue
> +            <span :class="'field'" v-html="query.typeOf.name"></span>
Thanks. Have changed then to inline css

2024-10-17 11:33 UTC, DavidStables commented on ui/src/components/directory/viewer/QueryDisplay.vue
> +            <span class="include-title" style="color: green">with the following features</span>
Done (hopefully got them all)

2024-10-17 14:25 UTC, DavidStables commented on ui/src/components/directory/viewer/QueryDisplay.vue
> +              />
Thanks. have done

2024-10-17 14:27 UTC, DavidStables commented on ui/src/components/directory/viewer/QueryDisplay.vue
> +                  :style="'color: blue'"
Done, hopefully done the rest

2024-10-17 15:39 UTC, DavidStables commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color: rgb(138, 67, 138) !important;
ok

2024-10-17 15:39 UTC, DavidStables commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color: orange;
ok

2024-10-17 15:40 UTC, DavidStables commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color : rgb(180, 48, 190);
ok

2024-10-17 15:40 UTC, DavidStables commented on ui/src/components/query/viewer/RecursiveWhereDisplay.vue
> +  color : rgb(0, 102, 102);
ok

2024-10-24 09:20 UTC, matt-voror requested changes

2024-10-24 09:20 UTC, matt-voror commented on ui/src/services/QueryService.ts
> +      params: { includeLogicDesc: includeLogicDesc }
Can't combine POST body and request params. IMAPI will ignore request params. Create a new request model.

2024-10-24 14:22 UTC, VororRich approved these changes

2024-10-24 14:24 UTC, VororRich approved these changes

2024-10-24 14:25 UTC, merged